# Generated by Django 5.2.6 on 2025-09-03 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_language_movie_genres_movie_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
